require:
- 'rubocop-rspec'

AllCops:
  NewCops: enable
  SuggestExtensions: false


# Bundler

Bundler/OrderedGems:
  Enabled: false

# Layout

Layout/AccessModifierIndentation:
  Enabled: false

Layout/CaseIndentation:
  Enabled: true
  IndentOneStep: true

Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

# This cop does not seem to properly detect some alignment spacings.
Layout/ExtraSpacing:
  Enabled: false

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: always_inspect

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationStyle:
  Enabled: true
  EnforcedStyle: tabs

Layout/IndentationWidth:
  Enabled: true
  Width: 1

Layout/LeadingEmptyLines:
  Enabled: true

Layout/LineLength:
  Enabled: false

Layout/SpaceAroundBlockParameters:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true
  EnforcedStyle: no_space

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: true
  AllowForAlignment: true
  EnforcedStyleForExponentOperator: no_space

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceBeforeComma:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: true
  Exclude:
    - 'spec/**/*'

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/SpaceInsideReferenceBrackets:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: true
  EnforcedStyle: final_newline

# Trailing whitespace is actually not wanted, but Rubocop does not have an option to allow indenting empty lines.
Layout/TrailingWhitespace:
  Enabled: false

# Lint

Lint/UnusedBlockArgument:
  Exclude:
    - 'spec/**/*'

Lint/UselessAssignment:
  Exclude:
    - 'bin/console'

# Naming

# TODO: Decide on a naming scheme or remove this TODO.
Naming/VariableNumber:
  Enabled: false

# RSpec

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: true
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

# Metrics

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# RSpec

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribedClass:
  Enabled: true
  EnforcedStyle: explicit

# Style

Style/AccessorGrouping:
  Enabled: true
  EnforcedStyle: separated

Style/BarePercentLiterals:
  Enabled: true
  EnforcedStyle: percent_q

Style/Documentation:
  Enabled: false

Style/EmptyBlockParameter:
  Enabled: false

Style/EmptyElse:
  Enabled: true
  EnforcedStyle: empty

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedIfElseCondition:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RaiseArgs:
  Enabled: true
  EnforcedStyle: exploded

Style/RedundantSelf:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
